[build]
  command = "npm run build" # your build command
  publish = "./dist" # where your production ready client code lives AFTER your build command has run
  ### functions = "./functions" # where your production ready lambda functions live AFTER your build command has run

[functions]
  directory = "./functions"

[[redirects]]
  from = "/next-change.json"
  to = "/.netlify/functions/next-change"
  status = 200
[[redirects]]
  from = "/testindex"
  to = "/.netlify/functions/index"
  status = 200
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
